name: Set up Node and PNPM packages with caching
description: Set up Node and PNPM packages with caching

runs:
  using: "composite"
  steps:
    - uses: pnpm/action-setup@v2
      with:
        version: 7
        
    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'pnpm'

    - name: Install packages
      run: pnpm install --frozen-lockfile
      shell: bash
