name: Set up Node and Yarn packages with caching

runs:
  using: "composite"
  steps:
    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    # this step will be obsolete soon hopefully
    - name: Enable corepack
      run: corepack enable
      shell: bash

    - name: Get yarn cache directory path
      id: yarn-cache-dir-path
      run: echo 'dir=$(yarn cache dir)' >> $GITHUB_OUTPUT
      shell: bash

    - name: Cache yarn downloads and dependencies
      uses: actions/cache@v3
      id: yarn-cache
      with:
        path: |
          ${{ steps.yarn-cache-dir-path.outputs.dir }}
          **/node_modules
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}

    - name: Set yarn version
      if: steps.yarn-cache.outputs.cache-hit != 'true'
      run: |
        yarn set version $( grep -Po 'packageManager": "yarn@\K[^"]+' package.json )
      shell: bash

    - name: Install packages
      if: steps.yarn-cache.outputs.cache-hit != 'true'
      run: yarn install --frozen-lockfile
      shell: bash
