# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Publish SDK package

on:
  push:
    branches:
      - main

jobs:
  setup:
    name: Set up Node and Yarn packages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node and Yarn packages with caching
        uses: ./.github/actions/install-and-cache-node-and-yarn

  lint:
    name: Run linter check
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node and Yarn packages with caching
        uses: ./.github/actions/install-and-cache-node-and-yarn

      - name: Run linter check
        run: yarn lint:nofix

  prettier:
    name: Run prettier check
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node and Yarn packages with caching
        uses: ./.github/actions/install-and-cache-node-and-yarn

      - name: Run prettier check
        run: yarn format:check

  build:
    name: Build and cache package
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node and Yarn packages with caching
        uses: ./.github/actions/install-and-cache-node-and-yarn

      - name: Build package
        run: yarn build

      - name: Cache package
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: |
            dist
            package.json
            README.md

  browserify:
    name: Browserify and tiniyfy code
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Restore dist
        uses: actions/download-artifact@v3
        with:
          name: dist

      - name: Set up Node and Yarn packages with caching
        uses: ./.github/actions/install-and-cache-node-and-yarn

      - name: Run browserify and tinyify
        run: yarn browserify && yarn tinyify

      - name: Cache package
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: |
            dist
            package.json
            README.md

  publish:
    name: Publish package
    needs: browserify
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Restore dist
        uses: actions/download-artifact@v3
        with:
          name: dist

      - name: Setup Node (using cache)
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Enable corepack
        run: corepack enable

      - name: Publish package
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
