# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Publish SDK package

on:
  push:
    branches:
      - main

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node (using cache)
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'

      - name: Enable corepack
        run: corepack enable

      - name: Install dependencies
        run: yarn install

  lint:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node (using cache)
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'

      - name: Enable corepack
        run: corepack enable

      - name: Run linter check
        run: yarn lint:nofix

  prettier:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node (using cache)
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'

      - name: Enable corepack
        run: corepack enable

      - name: Run prettier check
        run: yarn format:check

  build:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node (using cache)
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'

      - name: Enable corepack
        run: corepack enable

      - name: Build package
        run: yarn build

      - name: Cache dist
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist

  publish:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node (using cache)
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'
          registry-url: https://npm.pkg.github.com/

      - name: Enable corepack
        run: corepack enable

      - name: Restore dist
        uses: actions/download-artifact@v3
        with:
          name: dist

      - name: Publish package
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
